project_structure:
    build: build
    contracts: contracts
    interface: contracts/interface
    scripts: scripts
    tests: tests

networks:
  default: development

  development:
    cmd_settings:
      gas_limit: 40000000
      accounts: 100
      default_balance: 100000000
      mnemonic: clock radar mass judge dismiss just intact mind resemble fringe diary casino
      evm_version: berlin
      port: 8546
      unlimited_contract_size: true

compiler:
  solc:
    version: 0.8.4
    remappings:
      - '@openzeppelin/contracts=node_modules/@openzeppelin/contracts'

hypothesis:
  max_examples: 10
