[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "tests/foundry"
cache_path = "forge-cache"

solc = "0.8.4"

[fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
